[[zbar]]
arch = "aarch64"
git-tree-sha1 = "3e34c7fd413e23d8035bf8a54ec14fadaac23d7f"
os = "macos"

    [[zbar.download]]
    sha256 = "c6927e006c51fb0669896cddd47500bb0467a548bae72c348e9e3a364698b826"
    url = "https://github.com/JuliaBinaryWrappers/zbar_jll.jl/releases/download/zbar-v0.23.93+0/zbar.v0.23.93.aarch64-apple-darwin.tar.gz"
[[zbar]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "898471c1baee76321da964dd9c3790456ab06423"
libc = "glibc"
os = "linux"

    [[zbar.download]]
    sha256 = "e2367ea28e96089d800fce94ba2659844f52442832142b1dbbcf1ce0ff247db7"
    url = "https://github.com/JuliaBinaryWrappers/zbar_jll.jl/releases/download/zbar-v0.23.93+0/zbar.v0.23.93.aarch64-linux-gnu-cxx03.tar.gz"
[[zbar]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3fd108f1a457294c6ec7c4232f7745857f557e17"
libc = "glibc"
os = "linux"

    [[zbar.download]]
    sha256 = "807121d6e0ace9a3ed9de94f4a766c99a8751b2416428bd59d369c87ab5e3172"
    url = "https://github.com/JuliaBinaryWrappers/zbar_jll.jl/releases/download/zbar-v0.23.93+0/zbar.v0.23.93.aarch64-linux-gnu-cxx11.tar.gz"
[[zbar]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "063a57c028251eb49a56d1bf6dc7a8c82620b021"
libc = "musl"
os = "linux"

    [[zbar.download]]
    sha256 = "d12af448c1761dc49e3d0fa8a80be514b2dc226d9ab16da0667f522265f94d21"
    url = "https://github.com/JuliaBinaryWrappers/zbar_jll.jl/releases/download/zbar-v0.23.93+0/zbar.v0.23.93.aarch64-linux-musl-cxx03.tar.gz"
[[zbar]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fec3a0e613010905c5cf4aa27af8830fa293e845"
libc = "musl"
os = "linux"

    [[zbar.download]]
    sha256 = "8512f72c31f8d1e0e590870b55d0a43140686b53ac0fdff122a74e2de783ccc9"
    url = "https://github.com/JuliaBinaryWrappers/zbar_jll.jl/releases/download/zbar-v0.23.93+0/zbar.v0.23.93.aarch64-linux-musl-cxx11.tar.gz"
[[zbar]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0034ec3989038aa2229730e20c210f809b1d1482"
libc = "glibc"
os = "linux"

    [[zbar.download]]
    sha256 = "eb1ab681f410d30b044a4fdc2289c5d72e96f4d32ab4bff45be4a5c2b78c3be8"
    url = "https://github.com/JuliaBinaryWrappers/zbar_jll.jl/releases/download/zbar-v0.23.93+0/zbar.v0.23.93.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[zbar]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0f4bba3e60e18fddcd14f69e9f0ec58015206e36"
libc = "glibc"
os = "linux"

    [[zbar.download]]
    sha256 = "3dd479c290723277d438f645762cc1178599c81009ebeb93394b73022939b64d"
    url = "https://github.com/JuliaBinaryWrappers/zbar_jll.jl/releases/download/zbar-v0.23.93+0/zbar.v0.23.93.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[zbar]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c6938f973f19242783fa5bf2e1d9b069570de477"
libc = "musl"
os = "linux"

    [[zbar.download]]
    sha256 = "2a64d6785ec434cc84ef603fe5c2a053791668c0f9d5f6a776d9da0bc053101e"
    url = "https://github.com/JuliaBinaryWrappers/zbar_jll.jl/releases/download/zbar-v0.23.93+0/zbar.v0.23.93.armv6l-linux-musleabihf-cxx03.tar.gz"
[[zbar]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1ce3a154398a02b645aef676425ee3f2d8c7ac73"
libc = "musl"
os = "linux"

    [[zbar.download]]
    sha256 = "69627f3d42e3a853216cf07597ce0f36e1ccbb346788025fdc626c5a41370c83"
    url = "https://github.com/JuliaBinaryWrappers/zbar_jll.jl/releases/download/zbar-v0.23.93+0/zbar.v0.23.93.armv6l-linux-musleabihf-cxx11.tar.gz"
[[zbar]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a9f4b2f83e2cfa6a9c411a1ad83f190745b9b538"
libc = "glibc"
os = "linux"

    [[zbar.download]]
    sha256 = "4f75141869427758a8e19e176e110ff5be24da666df0773253b5cfbd060ca7c7"
    url = "https://github.com/JuliaBinaryWrappers/zbar_jll.jl/releases/download/zbar-v0.23.93+0/zbar.v0.23.93.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[zbar]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d7ce3258dbc41fc8060f81484704ce8b22d5e321"
libc = "glibc"
os = "linux"

    [[zbar.download]]
    sha256 = "cbe78aa0b975cc51342d30171ab89ec27a2b7dc4fd424a84249885887d38a4e3"
    url = "https://github.com/JuliaBinaryWrappers/zbar_jll.jl/releases/download/zbar-v0.23.93+0/zbar.v0.23.93.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[zbar]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "096b5aeabf05f39eed6b0af0d6343a83b79fb953"
libc = "musl"
os = "linux"

    [[zbar.download]]
    sha256 = "07d7a67481dd4d5e5e0b6159534a7f136208fc5eee5871d01ae154ace7efcc31"
    url = "https://github.com/JuliaBinaryWrappers/zbar_jll.jl/releases/download/zbar-v0.23.93+0/zbar.v0.23.93.armv7l-linux-musleabihf-cxx03.tar.gz"
[[zbar]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "35803dc57dacfa956d6308126fab55f616c4cf13"
libc = "musl"
os = "linux"

    [[zbar.download]]
    sha256 = "e02c19a2b9adf6c32efaa8fd62948d26d3c656f81de1e721457b84f1d4089b92"
    url = "https://github.com/JuliaBinaryWrappers/zbar_jll.jl/releases/download/zbar-v0.23.93+0/zbar.v0.23.93.armv7l-linux-musleabihf-cxx11.tar.gz"
[[zbar]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f92d6fb4b0c589ab6713bb64bd6ae88eab8ec9cb"
libc = "glibc"
os = "linux"

    [[zbar.download]]
    sha256 = "a4401dc9395da3645ce4bd6db9769bfac2406e11c5ef6fa3a93d460857d93d0d"
    url = "https://github.com/JuliaBinaryWrappers/zbar_jll.jl/releases/download/zbar-v0.23.93+0/zbar.v0.23.93.i686-linux-gnu-cxx03.tar.gz"
[[zbar]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a7decf479e8617a95aed310a421effed61e0d790"
libc = "glibc"
os = "linux"

    [[zbar.download]]
    sha256 = "0196980276aefff341d99ff26ebdde00d145a9b99277a1724a1ab014312685a4"
    url = "https://github.com/JuliaBinaryWrappers/zbar_jll.jl/releases/download/zbar-v0.23.93+0/zbar.v0.23.93.i686-linux-gnu-cxx11.tar.gz"
[[zbar]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e8a22c7d3498da32d1e53eb9c0196d046916242a"
libc = "musl"
os = "linux"

    [[zbar.download]]
    sha256 = "254a54b7a5ab560045ff62c63047e9ef2c890fd9ae70a1c0f7b9408605a68088"
    url = "https://github.com/JuliaBinaryWrappers/zbar_jll.jl/releases/download/zbar-v0.23.93+0/zbar.v0.23.93.i686-linux-musl-cxx03.tar.gz"
[[zbar]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1624de8a82b0f0760494277a510cf217ddd8e494"
libc = "musl"
os = "linux"

    [[zbar.download]]
    sha256 = "f371b1f73b5379eef221570d0e18eeecd77324cf82b384c14fb4a83201ef4c44"
    url = "https://github.com/JuliaBinaryWrappers/zbar_jll.jl/releases/download/zbar-v0.23.93+0/zbar.v0.23.93.i686-linux-musl-cxx11.tar.gz"
[[zbar]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4207b26b03d5f98550a0deb572cc1d6262175120"
os = "windows"

    [[zbar.download]]
    sha256 = "44e18a982e82010b0609f4d55ef13d067d3e6371789ff85b4725769d5249c9e5"
    url = "https://github.com/JuliaBinaryWrappers/zbar_jll.jl/releases/download/zbar-v0.23.93+0/zbar.v0.23.93.i686-w64-mingw32-cxx03.tar.gz"
[[zbar]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1047c84aa0c116c4797bfecded7e69f8b67cbeab"
os = "windows"

    [[zbar.download]]
    sha256 = "9cc8f6da45c78c5ff0fe119e8f8da1dc846ff6748b1827cbd2c1d318afba377c"
    url = "https://github.com/JuliaBinaryWrappers/zbar_jll.jl/releases/download/zbar-v0.23.93+0/zbar.v0.23.93.i686-w64-mingw32-cxx11.tar.gz"
[[zbar]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bc7e218fd23587657e3f60ffb1f3393497bf49d7"
libc = "glibc"
os = "linux"

    [[zbar.download]]
    sha256 = "4900aeabdf96cbeb5b98a516675e0bef79ea3b84015ee87e4f1e7d755a4113d4"
    url = "https://github.com/JuliaBinaryWrappers/zbar_jll.jl/releases/download/zbar-v0.23.93+0/zbar.v0.23.93.powerpc64le-linux-gnu-cxx03.tar.gz"
[[zbar]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9bcdf32ca03937bbdd33727a8eede968f8c1cbca"
libc = "glibc"
os = "linux"

    [[zbar.download]]
    sha256 = "ee845c4742b80dfa891933580399ab31c654482641e5e95a91074a768d40bea4"
    url = "https://github.com/JuliaBinaryWrappers/zbar_jll.jl/releases/download/zbar-v0.23.93+0/zbar.v0.23.93.powerpc64le-linux-gnu-cxx11.tar.gz"
[[zbar]]
arch = "x86_64"
git-tree-sha1 = "9a5d5f2fa87f8e6c1fb4876315363dcf251ce2f1"
os = "macos"

    [[zbar.download]]
    sha256 = "43b7c36773fd70022a60d2589718bb534affe607d785c616a5627c6916d71220"
    url = "https://github.com/JuliaBinaryWrappers/zbar_jll.jl/releases/download/zbar-v0.23.93+0/zbar.v0.23.93.x86_64-apple-darwin.tar.gz"
[[zbar]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d0be44b18bebaf6712a4fcd567f682f5c7f5f54b"
libc = "glibc"
os = "linux"

    [[zbar.download]]
    sha256 = "6a837d8ee98c7e27431b5a165eb452ae2e08ab84df5761b21ed3331696ad378d"
    url = "https://github.com/JuliaBinaryWrappers/zbar_jll.jl/releases/download/zbar-v0.23.93+0/zbar.v0.23.93.x86_64-linux-gnu-cxx03.tar.gz"
[[zbar]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "eefccf3ca18187de1c3fe34bc7190a67126bfc86"
libc = "glibc"
os = "linux"

    [[zbar.download]]
    sha256 = "188e68ceecdaf4ca13c939bfa05dcdbdf6cace31b597b94b786bf170392333da"
    url = "https://github.com/JuliaBinaryWrappers/zbar_jll.jl/releases/download/zbar-v0.23.93+0/zbar.v0.23.93.x86_64-linux-gnu-cxx11.tar.gz"
[[zbar]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c467cc38d65789fdff7da8efdd3c02ee03fe7c79"
libc = "musl"
os = "linux"

    [[zbar.download]]
    sha256 = "a2f9f7741bc5808320c00279e2a202a071f76c4001eec102817b339f3550fcd0"
    url = "https://github.com/JuliaBinaryWrappers/zbar_jll.jl/releases/download/zbar-v0.23.93+0/zbar.v0.23.93.x86_64-linux-musl-cxx03.tar.gz"
[[zbar]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0aeb14998c7d2fda9a613885347898a29865b820"
libc = "musl"
os = "linux"

    [[zbar.download]]
    sha256 = "1c10cad68b7c79ae1a0e735bbfe611a5c42143509f749caf1d09fb3379c53955"
    url = "https://github.com/JuliaBinaryWrappers/zbar_jll.jl/releases/download/zbar-v0.23.93+0/zbar.v0.23.93.x86_64-linux-musl-cxx11.tar.gz"
[[zbar]]
arch = "x86_64"
git-tree-sha1 = "632ef75e12cafe891c12126582b3d5cf6c998132"
os = "freebsd"

    [[zbar.download]]
    sha256 = "04406a2d524919e6961dbc3618a2824c8b47fcfd6ca2a6eeff4bac9dcb57c90d"
    url = "https://github.com/JuliaBinaryWrappers/zbar_jll.jl/releases/download/zbar-v0.23.93+0/zbar.v0.23.93.x86_64-unknown-freebsd.tar.gz"
[[zbar]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3238747fa44fcda0ddfe67d154a313f792317ec8"
os = "windows"

    [[zbar.download]]
    sha256 = "6af16042df18efb5f31153000eb471f7a91ea78832e7faa5efa51cc95c2bcf66"
    url = "https://github.com/JuliaBinaryWrappers/zbar_jll.jl/releases/download/zbar-v0.23.93+0/zbar.v0.23.93.x86_64-w64-mingw32-cxx03.tar.gz"
[[zbar]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a9816126e626acf28c0397da232e5f321921825e"
os = "windows"

    [[zbar.download]]
    sha256 = "fde5ec0958e2bb2f5d6026543d7b0cb91339ac596579c22f9449c56f2d9456b1"
    url = "https://github.com/JuliaBinaryWrappers/zbar_jll.jl/releases/download/zbar-v0.23.93+0/zbar.v0.23.93.x86_64-w64-mingw32-cxx11.tar.gz"
